import test from 'node:test';
import assert from 'node:assert/strict';
import type {Course} from '../content/course.ts';
import {createSupportedAnswer,validateDraft,validateReview} from '../server/support-answer.ts';
import {AppError} from '../server/ai.ts';
const section={id:'source-1',title:'Test',page:1,text:'In this lesson, values are 120, 240, and NULL. WHERE keeps only TRUE.'};
const course:Course={id:'test',title:'Test',subtitle:'',hash:'test',builtin:false,createdAt:'',sections:[section]};
const claim={text:'The values are 120, 240, and NULL.',citations:[{sectionId:section.id,quote:'values are 120, 240, and NULL.'}]};
const draft={basis:'The source gives the three literal values.',insufficient:false,missing:'',claims:[claim]};
const good={answerabilityReason:'The requested values are explicitly established.',sourceCanAnswer:true,questionCovered:true,missing:'',claims:[{index:0,verdict:'supported',reason:'Every value matches.'}]};
const stats={totalDurationMs:1,promptTokens:1,outputTokens:1};
function pipeline(outputs:unknown[]){let calls=0;const inputs:unknown[]=[];const run=createSupportedAnswer({retrieve:async()=>[section],chat:async(_s,u)=>{inputs.push(JSON.parse(u));const item=outputs[calls++];assert.notEqual(item,undefined,'unexpected extra model call');const rawItem=(item as any)?.basis?{...(item as any),claims:(item as any).claims.map((c:any)=>({text:c.text,evidenceIds:['E1']}))}:item;return{raw:typeof rawItem==='string'?rawItem:JSON.stringify(rawItem),stats}}});return{run,calls:()=>calls,inputs};}
test('only reviewed claims form final answer; full question, answer and sources reach reviewer',async()=>{const p=pipeline([draft,good]);const r=await p.run(course,'Which values?');assert.equal(r.answer,claim.text);assert.equal(r.support.outcome,'supported');assert.equal(r.support.modelCalls,2);const review=p.inputs[1] as any;assert.equal(review.proposedAnswer,claim.text);assert.equal(review.question,'Which values?');assert.equal(review.sources[0].text,section.text)});
test('exact quote does not bypass a rejected semantic review; one draft retry can repair it',async()=>{const bad={...draft,claims:[{...claim,text:'The values are 120, 2:40, and NULL.'}]};const rejected={...good,questionCovered:false,claims:[{index:0,verdict:'contradicted',reason:'240 was changed into a time.'}]};const p=pipeline([bad,rejected,draft,good]);const r=await p.run(course,'Which values?');assert.equal(p.calls(),4);assert.equal(r.answer,claim.text);assert.match(r.attempts[0].raw!,/2:40/);assert.equal(r.support.outcome,'supported')});
test('every claim must be reviewed exactly once; duplicated, missing or inconsistent reviews fail',()=>{const d=validateDraft(draft,[section],'Which values?');assert.throws(()=>validateReview({...good,claims:[]},d));assert.throws(()=>validateReview({...good,claims:[good.claims[0],good.claims[0]]},d));assert.throws(()=>validateReview({...good,sourceCanAnswer:false},d));assert.throws(()=>validateDraft({...draft,answer:'unreviewed tail'},[section],'Which values?'));assert.throws(()=>validateDraft({...draft,claims:[{...claim,citations:[{sectionId:section.id,quote:'fabricated source quote'}]}]},[section],'Which values?'))});
test('missing premises produce fixed refusal, never the draft negative assertion',async()=>{const bad={...draft,claims:[{...claim,text:'A is not a candidate key.'}]};const review={answerabilityReason:'The requested attribute universe is not established.',sourceCanAnswer:false,questionCovered:false,missing:'The full relation attributes are absent.',claims:[{index:0,verdict:'not-stated',reason:'Cannot infer a negative claim from absence.'}]};const decline={basis:'The full relation attributes are missing.',insufficient:true,missing:'Full relation attributes are absent.',claims:[]};const r=await pipeline([bad,review,decline,{...review,claims:[]}]).run(course,'Is A a candidate key?');assert.equal(r.support.outcome,'insufficient');assert.equal(r.citations.length,0);assert.doesNotMatch(r.answer,/A is not/);assert.match(r.answer,/Missing information is not evidence/)});
test('premature draft refusal is itself reviewed and can be repaired',async()=>{const refusal={basis:'Check whether values are in source.',insufficient:true,missing:'Cannot find values.',claims:[]};const reconsider={answerabilityReason:'The requested values are present.',sourceCanAnswer:true,questionCovered:false,missing:'',claims:[]};const r=await pipeline([refusal,reconsider,draft,good]).run(course,'Which values?');assert.equal(r.support.outcome,'supported');assert.equal(r.attempts.length,4)});
test('failed checks remain unverified rather than falsely claiming source absence',async()=>{const badReview={...good,questionCovered:false};const r=await pipeline([draft,badReview,draft,badReview]).run(course,'List values and explain TRUE.');assert.equal(r.support.outcome,'unverified');assert.match(r.answer,/may contain the answer/);assert.equal(r.citations.length,0)});
test('malformed JSON raw outputs survive and retries stay bounded',async()=>{const p=pipeline(['{bad json','{another broken']);const r=await p.run(course,'Which values?');assert.equal(p.calls(),2);assert.equal(r.support.outcome,'unverified');assert.equal(r.attempts.filter(a=>a.raw).length,2);assert.equal(r.attempts.filter(a=>a.error).length,2)});
test('cancellation while reading a response does not become validation retry',async()=>{const controller=new AbortController();let calls=0;const run=createSupportedAnswer({retrieve:async()=>[section],chat:async()=>{calls++;controller.abort();throw new DOMException('body read aborted','AbortError')}});await assert.rejects(run(course,'Which values?','en',controller.signal),(e:any)=>e instanceof AppError&&e.status===499);assert.equal(calls,1)});
test('overall deadline includes retrieval and remains timeout, not user cancellation',async()=>{const run=createSupportedAnswer({timeoutMs:5,retrieve:async(_c,_q,signal)=>{await new Promise<void>((_resolve,reject)=>{signal!.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')),{once:true});setTimeout(()=>reject(Error('deadline was not signalled')),50)});return[section]},chat:async()=>{throw Error('model should not run')}});await assert.rejects(run(course,'Which values?'),(e:any)=>e instanceof AppError&&e.status===503&&/request limit/.test(e.message))});
test('unavailable model propagates without retries or an invented refusal',async()=>{let calls=0;const run=createSupportedAnswer({retrieve:async()=>[section],chat:async()=>{calls++;throw new AppError('Model unavailable',503)}});await assert.rejects(run(course,'Which values?'),(e:any)=>e.status===503);assert.equal(calls,1)});

test('a failed review retains its earlier draft and failed-stage audit',async()=>{let calls=0;const run=createSupportedAnswer({retrieve:async()=>[section],chat:async()=>{if(calls++===0)return{raw:JSON.stringify({...draft,claims:[{text:claim.text,evidenceIds:['E1']}]}),stats};throw new AppError('Model unavailable',503)}});await assert.rejects(run(course,'Which values?'),(error:any)=>{assert.equal(error.status,503);assert.equal(error.audit.modelCalls,2);assert.match(error.audit.attempts[0].raw,/E1/);assert.equal(error.audit.attempts[1].stage,'review');assert.match(error.audit.attempts[1].error,/unavailable/);return true})});

test('whitespace citations cannot exploit empty-string substring matching',()=>{assert.throws(()=>validateDraft({...draft,claims:[{...claim,citations:[{sectionId:section.id,quote:'        '}]}]},[section],'Which values?'),/non-padding/)});
test('retrieval response body timeout is actionable and retains its failure audit',async()=>{const run=createSupportedAnswer({retrieve:async()=>{throw new DOMException('body timeout','TimeoutError')},chat:async()=>{throw Error('must not run')}});await assert.rejects(run(course,'Which values?'),(e:any)=>e.status===503&&e.audit.modelCalls===0&&/timed out/.test(e.message))});

// These checks validate the protocol boundary, not the model's semantic judgment.
test('even an empty refusal review must explain whether the requested fact is established',()=>{
 const d=validateDraft({basis:'The requested value is absent.',insufficient:true,missing:'Value',claims:[]},[section],'Which value?');
 const review={answerabilityReason:'The sources do not establish the requested value.',sourceCanAnswer:false,questionCovered:false,missing:'Value',claims:[]};
 assert.deepEqual(validateReview(review,d),review);
 assert.throws(()=>validateReview({...review,answerabilityReason:'   '},d));
 const {answerabilityReason,...unreasoned}=review;assert.throws(()=>validateReview(unreasoned,d));
});
test('a review cannot accept full coverage while recording an omitted requirement',()=>{
 const d=validateDraft(draft,[section],'Which values?');
 assert.throws(()=>validateReview({...good,missing:'The repetition limit is omitted.'},d),/missing requirements/);
 const incomplete={...good,questionCovered:false,missing:'The repetition limit is omitted.'};
 assert.equal(validateReview(incomplete,d).questionCovered,false);
});
