export type Section = {id:string;title:string;page:number;text:string;textZh?:string;vector?:number[]};
export type Course = {id:string;title:string;subtitle:string;hash:string;builtin:boolean;sections:Section[];createdAt:string};
export type Question = {id:string;courseId:string;concept:string;kind:'diagnostic'|'transfer'|'generated';prompt:string;promptZh?:string;options:string[];optionsZh?:string[];correct:number;explanation:string;explanationZh?:string;misconceptions:string[];sourceIds:string[];pairedId?:string};
export const sections:Section[] = [
{id:'null-comparison',page:1,title:'NULL is not a value',text:'NULL represents missing or unknown information. It is not zero, an empty string, or a value equal to another NULL. Ordinary SQL comparisons involving NULL, including NULL = NULL and NULL <> 5, evaluate to UNKNOWN rather than TRUE or FALSE. Use IS NULL or IS NOT NULL to test missingness.',textZh:'NULL 表示缺失或未知信息。它不是零、空字符串，也不等于另一个 NULL。普通比较只要涉及 NULL（包括 NULL = NULL），结果就是 UNKNOWN。请用 IS NULL 或 IS NOT NULL 判断缺失。'},
{id:'null-where',page:1,title:'WHERE keeps only TRUE',text:'SQL uses TRUE, FALSE, and UNKNOWN in its three-valued logic. A WHERE clause keeps a row only when its predicate is TRUE; FALSE and UNKNOWN are both filtered out. For salaries 100, 200, and NULL, WHERE salary <> 100 returns only the row with 200. To include missing salaries, write salary <> 100 OR salary IS NULL.',textZh:'SQL 使用 TRUE、FALSE、UNKNOWN 三值逻辑。WHERE 仅保留条件为 TRUE 的行。工资为 100、200、NULL 时，salary <> 100 只返回 200。要包含缺失工资，使用 salary <> 100 OR salary IS NULL。'},
{id:'null-logic',page:2,title:'Combining unknown conditions',text:'In SQL three-valued logic, NOT UNKNOWN is UNKNOWN. TRUE OR UNKNOWN is TRUE, FALSE OR UNKNOWN is UNKNOWN, FALSE AND UNKNOWN is FALSE, and TRUE AND UNKNOWN is UNKNOWN. Thus NOT (salary = 100) still excludes rows with NULL salary in a WHERE clause.',textZh:'NOT UNKNOWN 仍为 UNKNOWN。TRUE OR UNKNOWN 为 TRUE，FALSE OR UNKNOWN 为 UNKNOWN，FALSE AND UNKNOWN 为 FALSE，TRUE AND UNKNOWN 为 UNKNOWN。因此 NOT (salary = 100) 仍会过滤 NULL。'},
{id:'null-count',page:2,title:'Counting rows versus values',text:'COUNT(*) counts all rows. COUNT(column) counts only rows where that column is not NULL. AVG(column) ignores NULL values rather than treating them as zero. For scores 10, 20, NULL: COUNT(*) = 3, COUNT(score) = 2, SUM(score) = 30 and AVG(score) = 15.',textZh:'COUNT(*) 计算全部行数。COUNT(列) 仅计算该列不为 NULL 的行。AVG 忽略 NULL，不把它当成零。10、20、NULL 的行数为 3，非空数为 2，总和为 30，平均值为 15。'},
{id:'null-not-in',page:3,title:'The NOT IN trap',text:'x NOT IN (1, NULL) behaves like x <> 1 AND x <> NULL. For x = 2 the result is TRUE AND UNKNOWN, which is UNKNOWN. For x = 1 the result is FALSE. No row passes WHERE x NOT IN (1, NULL). To avoid unexpected exclusion, remove NULL from the list or use an appropriate correlated NOT EXISTS condition.',textZh:'x NOT IN (1, NULL) 等价于 x <> 1 AND x <> NULL。x 为 2 时结果是 UNKNOWN，为 1 时结果为 FALSE，因此没有行能通过 WHERE。可移除列表中的 NULL，或使用适当的关联 NOT EXISTS。'},
{id:'keys',page:3,title:'Superkeys and candidate keys',text:'A superkey is a set of attributes that uniquely identifies a tuple in every legal instance of a relation. A candidate key is a minimal superkey: no proper subset is a superkey. Minimal means no removable attribute, not necessarily the smallest number of attributes among all keys. A relation can have multiple candidate keys. One is selected as the primary key.',textZh:'超键在每个合法实例中唯一标识元组。候选键是最小超键，即任何真子集都不是超键。最小是不可删除属性，不是所有键中属性数最少。一个关系可以有多个候选键，其中一个被选为主键。'},
{id:'key-example',page:4,title:'Minimality needs a check',text:'In Enrollment(Student, Course, Grade), suppose the only nontrivial dependency is Student,Course -> Grade. The set {Student,Course} is a candidate key. {Student,Course,Grade} is a superkey but not a candidate key because Grade can be removed. Student alone and Course alone need not be unique. Prime attributes are those belonging to at least one candidate key.',textZh:'在 Enrollment(Student, Course, Grade) 中，若唯一非平凡依赖是 Student,Course -> Grade，则 {Student,Course} 是候选键。包含 Grade 的三属性集合是超键但不是候选键。主属性是至少属于一个候选键的属性。'},
{id:'fd-definition',page:4,title:'Dependencies describe all legal data',text:'A functional dependency X -> Y means that any two tuples agreeing on all attributes of X must also agree on all attributes of Y in every legal instance. It does not mean that Y uniquely determines X. An observed table can disprove a proposed dependency with a counterexample, but one small table cannot establish a dependency for all legal future instances without domain constraints.',textZh:'X -> Y 表示每个合法实例中，X 相同的两行必须具有相同的 Y。它不意味着 Y -> X。一个反例可以推翻依赖，但没有反例的小表不能单独证明所有未来合法实例都满足依赖。'},
{id:'fd-trivial',page:5,title:'Trivial dependencies',text:'A dependency X -> Y is trivial if Y is a subset of X. For example {Student,Course} -> Student is trivial. Armstrong rules include reflexivity (subsets are determined), augmentation (add the same attributes to both sides), and transitivity (X -> Y and Y -> Z imply X -> Z). A dependency is a constraint, not a causal claim.',textZh:'若 Y 是 X 的子集，X -> Y 是平凡依赖。例如 {Student,Course} -> Student。Armstrong 公理包括自反、增广和传递；依赖描述约束，不描述因果关系。'},
{id:'closure',page:5,title:'Compute an attribute closure',text:'To compute X+ under functional dependencies, begin with X, repeatedly add the right-hand side of any dependency whose left-hand side is already included, and stop when no new attribute can be added. For R(A,B,C,D) with A -> B and B -> C, A+ = {A,B,C}; D is not in A+. AD is a candidate key because its closure is ABCD and neither A nor D alone determines all attributes.',textZh:'求 X+：从 X 开始，若某依赖的左侧已包含，就加入右侧，重复直到不再增加。R(A,B,C,D) 且 A -> B、B -> C 时，A+ 为 ABC，不含 D。AD 是候选键。'},
{id:'first-normal',page:6,title:'First normal form',text:'A relation is in first normal form (1NF) when attribute values are atomic within the chosen relational domain, rather than repeating groups or lists packed into a field. Splitting a Phones field containing multiple phone numbers into separate rows is a typical 1NF transformation. Being in 1NF does not remove partial or transitive functional dependencies.',textZh:'第一范式要求属性值在所选关系域中具有原子性，避免重复组或在字段中存放列表。将一个字段里的多个电话拆成独立行是常见转换。1NF 不会自动消除部分或传递依赖。'},
{id:'second-normal',page:6,title:'Second normal form',text:'A relation is in second normal form (2NF) if it is in 1NF and no non-prime attribute depends on a proper subset of any candidate key. Such a dependence is a partial dependency. In Enrollment(Student,Course,StudentName,Grade), with key {Student,Course} and Student -> StudentName, the non-prime StudentName partially depends on the key, so the relation violates 2NF.',textZh:'第二范式要求满足 1NF，且非主属性不依赖任何候选键的真子集。Enrollment 中键为 Student,Course，而 Student -> StudentName 时，StudentName 部分依赖该键，违反 2NF。'},
{id:'third-normal',page:7,title:'The precise 3NF test',text:'A relation is in third normal form (3NF) if, for every nontrivial functional dependency X -> A implied by its dependencies, either X is a superkey or A is a prime attribute. A prime attribute belongs to at least one candidate key. This prime-attribute exception makes 3NF weaker than BCNF. The informal slogan no transitive dependencies is not a complete definition.',textZh:'第三范式的精确定义：对每个非平凡依赖 X -> A，X 是超键，或者 A 是主属性。主属性例外使 3NF 弱于 BCNF。“没有传递依赖”不是完整定义。'},
{id:'bcnf',page:7,title:'BCNF removes the exception',text:'A relation is in Boyce-Codd normal form (BCNF) if the determinant of every nontrivial functional dependency is a superkey. BCNF does not allow the prime-attribute exception used by 3NF. Every BCNF relation is in 3NF, but a 3NF relation need not be in BCNF.',textZh:'BCNF 要求每个非平凡依赖的决定因素都是超键，没有 3NF 的主属性例外。BCNF 一定满足 3NF，但 3NF 不一定满足 BCNF。'},
{id:'normal-example',page:8,title:'A relation in 3NF but not BCNF',text:'Let R(Student,Course,Instructor) have dependencies Student,Course -> Instructor and Instructor -> Course. Candidate keys are {Student,Course} and {Student,Instructor}. All three attributes are prime. Instructor is not a superkey because it does not determine Student. Instructor -> Course therefore violates BCNF, but satisfies 3NF because Course is prime.',textZh:'R(Student,Course,Instructor) 满足 SC -> I、I -> C。候选键为 SC 与 SI，三个属性都是主属性。Instructor 不能决定 Student，不是超键；I -> C 违反 BCNF，但因 C 为主属性而满足 3NF。'},
{id:'anomalies',page:8,title:'Redundancy creates anomalies',text:'If Employee(EmpId,DeptId,DeptName) stores DeptName repeatedly and DeptId -> DeptName, changing a department name requires changing multiple employee rows. Failing to update all rows causes an update anomaly. Requiring an employee to record a new department causes an insertion anomaly; removing its last employee can lose department information, a deletion anomaly.',textZh:'员工表重复保存部门名称会带来更新异常；必须有员工才能记录部门会带来插入异常；删除最后一个员工导致部门信息丢失则是删除异常。'},
{id:'lossless',page:9,title:'Lossless decomposition',text:'A decomposition is lossless if joining the projections reconstructs exactly the original relation for every legal instance, without adding spurious tuples. For a binary decomposition into R1 and R2 under functional dependencies, losslessness holds if their common attributes functionally determine all attributes of R1 or all attributes of R2. Sharing any attribute alone is not sufficient.',textZh:'无损分解要求投影后的连接恰好重建每个合法原关系，不产生伪元组。二元分解中，公共属性决定其中任一子关系的全部属性即可保证无损。仅有共同属性并不充分。'},
{id:'preservation',page:9,title:'Dependency preservation',text:'A decomposition preserves dependencies if constraints on the individual decomposed relations suffice to enforce the original dependencies without joining relations. Losslessness and dependency preservation are different properties. A BCNF decomposition can be lossless while failing to preserve all dependencies; standard 3NF synthesis can achieve both losslessness and dependency preservation.',textZh:'保持依赖表示无需连接即可在各子关系上检查原依赖。无损和保持依赖是不同性质。BCNF 分解可无损但不保持全部依赖；标准 3NF 综合算法可同时实现二者。'},
{id:'join-filter',page:10,title:'Filtering a left join',text:'A LEFT JOIN retains unmatched rows from its left input, padding right-side columns with NULL. A subsequent WHERE right_column = some_value filters out those unmatched rows because the comparison is UNKNOWN. Placing a right-side match restriction in the ON clause instead can retain unmatched left rows, although the two queries then have different intended semantics.',textZh:'LEFT JOIN 保留左侧未匹配行并将右侧填为 NULL。之后 WHERE 右列 = 某值 会过滤这些行；把右侧匹配条件放在 ON 中可以保留左侧未匹配行，但语义不同。'},
{id:'scope',page:10,title:'What these notes do not establish',text:'These original teaching notes cover relational keys, functional dependencies, normal forms, decomposition, and selected SQL NULL semantics. They do not specify a particular vendor database version, recommend medical or financial actions, establish a student learning outcome, provide personal records, or define a university exam marking policy.',textZh:'这些原创讲义只覆盖关系键、函数依赖、范式、分解与部分 SQL NULL 语义，不规定厂商版本、医疗或财务决策、学生学习效果、个人记录或大学考试评分政策。'}
];
const q=(id:string,concept:string,kind:Question['kind'],prompt:string,options:string[],correct:number,explanation:string,sourceIds:string[],misconceptions:string[],pairedId?:string):Question=>({id,courseId:'database-foundations',concept,kind,prompt,options,correct,explanation,sourceIds,misconceptions,pairedId});
export const questions:Question[]=[
q('null-d','SQL NULL','diagnostic','Salaries are 100, 200, and NULL. Which rows survive WHERE salary <> 100?',['200 only','200 and NULL','All three rows','No rows'],0,'The comparison with NULL is UNKNOWN. WHERE keeps only TRUE, so only 200 survives.',['null-comparison','null-where'],['','You may be treating unknown as an ordinary value different from 100.','The row containing 100 fails the comparison.','The non-NULL value 200 makes the predicate TRUE.'],'null-t'),
q('null-t','SQL NULL','transfer','Prices are 10, 20, and NULL. Which condition returns 20 and NULL, but not 10?',['price <> 10','NOT (price = 10)','price <> 10 OR price IS NULL','price = NULL'],2,'IS NULL explicitly includes the missing price; negating an UNKNOWN comparison does not make it TRUE.',['null-where','null-logic'],['A comparison alone excludes missing prices.','NOT UNKNOWN remains UNKNOWN.','','NULL needs IS NULL, not equality.']),
q('count-d','Aggregates','diagnostic','Scores are 10, 20, and NULL. What are COUNT(*) and COUNT(score)?',['2 and 2','3 and 2','3 and 3','2 and 3'],1,'COUNT(*) counts rows; COUNT(score) ignores the NULL entry.',['null-count'],['COUNT(*) includes the row with NULL.','','COUNT(score) does not count NULL.','These two counts cannot be reversed.'],'count-t'),
q('count-t','Aggregates','transfer','Scores are 10, 20, and NULL. What is AVG(score)?',['10','15','30','UNKNOWN'],1,'The sum is 30 and there are two non-NULL scores, so AVG is 15.',['null-count'],['This treats NULL as zero and divides by all three rows.','','AVG divides the sum by the non-NULL count.','An individual missing value does not make this aggregate unknown.']),
q('notin-d','NOT IN','diagnostic','Which x passes WHERE x NOT IN (1, NULL), for x values 1 and 2?',['Only 1','Only 2','Both','Neither'],3,'For 1 the predicate is FALSE; for 2 it is UNKNOWN. Neither passes WHERE.',['null-not-in','null-where'],['1 appears in the list.','NULL in the list prevents TRUE for 2.','Neither value gives TRUE.',''],'notin-t'),
q('notin-t','NOT IN','transfer','For a known x = 2, what is the truth value of x <> 1 AND x <> NULL?',['TRUE','FALSE','UNKNOWN','A syntax error'],2,'TRUE AND UNKNOWN is UNKNOWN.',['null-not-in','null-logic'],['One operand is UNKNOWN.','Neither operand is FALSE.','','Comparisons with NULL are valid expressions.']),
q('key-d','Candidate keys','diagnostic','Enrollment(S,C,G) has only SC → G. Which is a candidate key?',['S','C','SC','SCG'],2,'SC determines every attribute and neither S nor C does. SCG is not minimal.',['keys','key-example'],['A student can take multiple courses.','A course can have multiple students.','','Uniqueness alone makes a superkey, not a candidate key.'],'key-t'),
q('key-t','Candidate keys','transfer','If both A and BC are minimal superkeys, which are candidate keys?',['A only because it is shorter','BC only','Both A and BC','Neither'],2,'Minimality is checked within each set, not by comparing key lengths.',['keys'],['Minimal does not mean globally shortest.','A is itself a minimal superkey.','','Both satisfy the definition.']),
q('fd-d','Functional dependencies','diagnostic','Two rows have the same X but different Y. What does this establish about X → Y?',['It holds','It is violated','It proves Y → X','Nothing can be concluded'],1,'One pair agreeing on X but disagreeing on Y is a counterexample.',['fd-definition'],['The rows violate the defining implication.','','The reverse dependency needs its own check.','A counterexample is sufficient to disprove it.'],'fd-t'),
q('fd-t','Functional dependencies','transfer','A small sample has no duplicate employee names. Does this prove Name → EmployeeId for all future legal data?',['Yes, by observation','No; domain constraints are needed','Yes, if sorted','Only when Name is text'],1,'A sample can disprove a dependency but cannot by itself establish a universal constraint.',['fd-definition'],['The sample may simply not contain a counterexample yet.','','Sorting does not establish constraints.','The data type does not establish uniqueness.']),
q('closure-d','Attribute closure','diagnostic','R(A,B,C,D) has A → B and B → C. What is A+?',['A','AB','ABC','ABCD'],2,'Start with A, add B, then C. No dependency can add D.',['closure'],['Apply A → B.','Apply B → C as well.','','D is not reachable from A.'],'closure-t'),
q('closure-t','Attribute closure','transfer','Under A → B and B → C in R(A,B,C,D), which is a candidate key?',['A','AB','AD','BCD'],2,'AD reaches ABCD. Removing A or D loses at least one attribute.',['closure','keys'],['A does not determine D.','Adding B does not obtain D.','','Nothing in BCD determines A.']),
q('2nf-d','Second normal form','diagnostic','Enrollment(S,C,Name,Grade), key SC, has S → Name. Why does it violate 2NF?',['Name is non-atomic','A non-prime attribute depends on part of the key','Every composite key violates 2NF','It has no primary key'],1,'Name is non-prime and depends on S, a proper subset of candidate key SC.',['second-normal'],['Atomicity is a separate 1NF issue.','','Composite keys are allowed.','A key is explicitly given.'],'2nf-t'),
q('2nf-t','Second normal form','transfer','A relation is in 1NF and every candidate key has one attribute. Can it have a nonempty proper-subset partial dependency on a key?',['Yes, always','No','Only with NULL','Only if it has two rows'],1,'A single-attribute key has no nonempty proper subset; this question excludes empty determinants.',['second-normal','keys'],['There is no nonempty part of a one-attribute key.','','NULL does not create a subset.','Row count is not the criterion.']),
q('bcnf-d','3NF vs BCNF','diagnostic','R(S,C,I) has SC → I and I → C; candidate keys are SC and SI. Which claim is correct?',['BCNF because C is prime','3NF but not BCNF','Neither 3NF nor BCNF','BCNF because I is a superkey'],1,'I is not a superkey. C is prime, so I → C satisfies 3NF but violates BCNF.',['third-normal','bcnf','normal-example'],['BCNF has no prime-attribute exception.','','The prime-attribute exception satisfies 3NF.','I cannot determine S.'],'bcnf-t'),
q('bcnf-t','3NF vs BCNF','transfer','Which condition suffices for a nontrivial X → A under 3NF but not necessarily BCNF?',['X is a superkey','A is prime while X is not a superkey','A is non-prime','X is a column'],1,'The prime-attribute exception is specific to 3NF.',['third-normal','bcnf'],['This satisfies both definitions.','','A non-prime right-hand side needs a superkey determinant.','A determinant can be one or more attributes.']),
q('lossless-d','Decomposition','diagnostic','R(A,B,C) with A → B is decomposed into AB and AC. Why is it lossless?',['Any shared column is enough','The common A determines AB','Because C is unique','Because all decompositions are lossless'],1,'The intersection A determines all of AB, satisfying the binary lossless test.',['lossless'],['A shared attribute must determine a component.','','C uniqueness was not given.','Some decompositions add spurious tuples.'],'lossless-t'),
q('lossless-t','Decomposition','transfer','Does a lossless BCNF decomposition necessarily preserve every functional dependency?',['Yes','No','Only with fewer than ten rows','Only when names are unique'],1,'Losslessness and dependency preservation differ; BCNF decomposition can lose dependency preservation.',['preservation'],['Lossless reconstruction does not guarantee local enforcement.','','This is a schema property.','Attribute names are irrelevant.']),
q('join-d','LEFT JOIN','diagnostic','After a LEFT JOIN, WHERE right.status = \'active\' is applied. What happens to unmatched left rows?',['They always stay','They are filtered out','They become active','The query is invalid'],1,'Their right-side status is NULL, so the WHERE comparison is UNKNOWN and filters them out.',['join-filter','null-where'],['A later WHERE can remove rows retained by the join.','','A comparison does not fill missing values.','The query is valid, but may not match the intent.'],'join-t'),
q('join-t','LEFT JOIN','transfer','To retain every left row while matching only active right rows, where should the active restriction be placed?',['In WHERE right.status = \'active\'','In the LEFT JOIN ON condition','In ORDER BY','In LIMIT'],1,'A right-side match restriction in ON limits matches while preserving unmatched left rows.',['join-filter'],['This removes unmatched rows after the join.','','Ordering does not define join matches.','LIMIT changes row count, not match semantics.'])
];
