import express from 'express';
import multer from 'multer';
import {randomUUID} from 'node:crypto';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {z} from 'zod';
import {db,getCourses,getCourse,saveCourse,getQuestion,saveQuestion,listQuestions,publicQuestion,publicCourse,history} from './store.ts';
import {AppError} from './ai.ts';
import {modelStatus} from './local-model.ts';
import {supportedAnswer} from './support-answer.ts';
import {generatePractice} from './practice-generation.ts';
import {aiReportLines} from './report.ts';
import {importDocument} from './import.ts';
import {planPractice,validatePlannedPractice,ensureUnusedPractice} from './practice-planner.ts';
import {installationIdentity} from '../scripts/identity.mjs';
const app=express(),port=Number(process.env.PORT||4317);
const identity=installationIdentity();
app.disable('x-powered-by');
app.use((req,res,next)=>{if(!['127.0.0.1','localhost','[::1]'].includes((req.headers.host||'').replace(/:\d+$/,'')))return res.status(403).json({error:'Local access only.'});const origin=req.headers.origin;if(origin&&!['http://127.0.0.1:'+port,'http://localhost:'+port].includes(origin))return res.status(403).json({error:'Cross-origin requests are not allowed.'});res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');next();});
app.use(express.json({limit:'64kb'}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:1}});
const course=(id:string)=>{const c=getCourse(id);if(!c)throw new AppError('Course not found.',404);return c;};
const cancellation=(res:express.Response)=>{const c=new AbortController();res.on('close',()=>{if(!res.writableEnded)c.abort()});return c.signal;};
app.get('/api/status',async(_req,res)=>res.json(await modelStatus()));
app.get('/api/identity',(_req,res)=>res.json(identity));
app.get('/api/courses',(_req,res)=>res.json(getCourses().map(publicCourse)));
app.get('/api/courses/:id/questions',(req,res)=>res.json(listQuestions(req.params.id).map(publicQuestion)));
app.get('/api/courses/:id/history',(req,res)=>{course(req.params.id);res.json(history(req.params.id));});
app.post('/api/import',upload.single('file'),async(req,res)=>{if(!req.file)throw new AppError('Choose a file first.');const c=await importDocument(req.file.originalname,req.file.buffer);saveCourse(c);res.status(201).json(publicCourse(c));});
app.post('/api/attempt', (req,res)=>{const b=z.object({questionId:z.string(),chosen:z.number().int().min(0).max(3),confidence:z.enum(['unsure','somewhat','sure'])}).parse(req.body);const q=getQuestion(b.questionId);if(!q)throw new AppError('Question not found.',404);const c=course(q.courseId);const result={id:randomUUID(),questionId:q.id,concept:q.concept,kind:q.kind,prompt:q.prompt,options:q.options,chosen:b.chosen,correct:q.correct,isCorrect:b.chosen===q.correct,confidence:b.confidence,explanation:q.explanation,misconception:q.misconceptions[b.chosen]||'',sourceIds:q.sourceIds,sourceHash:c.hash,createdAt:new Date().toISOString()};db.prepare('INSERT INTO attempts(courseId,data) VALUES (?,?)').run(q.courseId,JSON.stringify(result));res.json(result);});
app.post('/api/ask',async(req,res)=>{const b=z.object({courseId:z.string(),question:z.string().trim().min(3).max(1200),language:z.enum(['en','zh']).default('en')}).parse(req.body);const c=course(b.courseId);const signal=cancellation(res);const r=await supportedAnswer(c,b.question,b.language,signal);if(signal.aborted)throw new AppError('Generation cancelled.',499);const record={question:b.question,...r,sourceHash:c.hash,createdAt:new Date().toISOString()};db.prepare('INSERT INTO chats(courseId,data) VALUES (?,?)').run(c.id,JSON.stringify(record));res.json(record);});
app.post('/api/generate-question',async(req,res)=>{
 const b=z.object({courseId:z.string(),language:z.enum(['en','zh']).default('en'),sectionId:z.string().min(1).max(200).optional()}).parse(req.body);
 const c=course(b.courseId),signal=cancellation(res);
 const plan=planPractice(c,listQuestions(c.id),b.sectionId);
 const generated=validatePlannedPractice(plan,await generatePractice(plan.courseView,b.language,signal),c);
 if(signal.aborted)throw new AppError('Generation cancelled.',499);
 const q={...generated,id:randomUUID(),courseId:c.id,kind:'generated' as const,misconceptions:['','','','']};
 // No await between duplicate checking and insertion: concurrent completions cannot both save the same sentence.
 db.transaction(()=>{ensureUnusedPractice(listQuestions(c.id),generated);saveQuestion(q);})();
 res.json(publicQuestion(q));
});
app.get('/api/courses/:id/report',(req,res)=>{const c=course(req.params.id),h=history(c.id);const lines=['# TraceLearn — Evidence of practice','',`Course: ${c.title}`,`Source SHA-256: ${c.hash}`,`Exported: ${new Date().toISOString()}`,'','This is a practice record, not a validated measure of mastery or learning gains. AI-generated explanations may be wrong; consult the quoted source.','',`Attempts: ${h.attempts.length}`,`Correct attempts: ${h.attempts.filter(a=>a.isCorrect).length}`,'','## Practice history',...h.attempts.flatMap((a,i)=>['',`### ${i+1}. ${a.concept} / ${a.kind}`,a.prompt,`Chosen: ${a.options[a.chosen]}`,`Correct answer: ${a.options[a.correct]}`,`Result: ${a.isCorrect?'Correct':'Needs review'}; self-reported confidence: ${a.confidence}`,a.explanation,`Sources: ${a.sourceIds.join(', ')}`,`Time: ${a.createdAt}`]),'','## Local AI questions',...h.chats.flatMap(aiReportLines)];res.setHeader('Content-Type','text/markdown; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="TraceLearn-learning-report.md"');res.send(lines.join('\n'));});
if(existsSync('dist/index.html')){app.use(express.static('dist'));app.get('/{*path}',(_req,res)=>res.sendFile(resolve('dist/index.html')));}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{const status=err instanceof z.ZodError?400:err.code==='LIMIT_FILE_SIZE'?413:err.status||500;const message=err instanceof z.ZodError?'Please check the input values.':err.code==='LIMIT_FILE_SIZE'?'Maximum file size is 10 MB.':status===500?'Unexpected local error. Please retry.':err.message;if(status===500)console.error(err);if(!res.headersSent)res.status(status).json({error:message});});
app.listen(port,'127.0.0.1',()=>console.log(`TraceLearn http://127.0.0.1:${port}`));
