import {spawn} from 'node:child_process';import {request as httpRequest} from 'node:http';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
const dir=mkdtempSync(join(tmpdir(),'tracelearn-http-'));const child=spawn(process.execPath,['--import','tsx','server/index.ts'],{env:{...process.env,PORT:'4320',TRACELEARN_DATA:dir},stdio:'pipe'});const base='http://127.0.0.1:4320';const checks:string[]=[];
try{for(let i=0;i<100;i++){try{await fetch(base+'/api/courses');break}catch{await new Promise(r=>setTimeout(r,100))}}const request=(path:string,body:any,headers:any={})=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const qs=await(await fetch(base+'/api/courses/database-foundations/questions')).json();assert.equal(qs.length,20);assert.ok(qs.every((q:any)=>!('correct'in q)));checks.push('Answers hidden from pre-attempt question API');
let r=await request('/api/attempt',{questionId:'null-d',chosen:9,confidence:'sure'});assert.equal(r.status,400);checks.push('Invalid answer index rejected');
r=await request('/api/attempt',{questionId:'null-d',chosen:1,confidence:'sure'});const a=await r.json();assert.equal(a.isCorrect,false);assert.equal(a.correct,0);checks.push('Wrong answer yields deterministic feedback');
r=await request('/api/attempt',{questionId:'null-t',chosen:2,confidence:'somewhat'});assert.equal((await r.json()).isCorrect,true);checks.push('Transfer answer graded correctly');
const h=await(await fetch(base+'/api/courses/database-foundations/history')).json();assert.equal(h.attempts.length,2);checks.push('History persists in SQLite');
const report=await(await fetch(base+'/api/courses/database-foundations/report')).text();assert.match(report,/Source SHA-256/);assert.match(report,/Correct attempts: 1/);checks.push('Report contains attempts and provenance');
r=await request('/api/ask',{courseId:'database-foundations',question:'x'.repeat(1201)});assert.equal(r.status,400);checks.push('Oversized prompt rejected');
r=await request('/api/attempt',{questionId:'null-d',chosen:0,confidence:'sure'},{Origin:'https://malicious.example'});assert.equal(r.status,403);checks.push('Cross-origin mutation blocked');
const hostStatus=await new Promise<number|undefined>((resolve,reject)=>{const request=httpRequest(base+'/api/courses',{headers:{Host:'malicious.example'}},res=>{res.resume();resolve(res.statusCode)});request.on('error',reject);request.end()});assert.equal(hostStatus,403);checks.push('DNS rebinding Host rejected');
let f=new FormData();f.append('file',new Blob(['# Sample\nA superkey identifies a tuple uniquely.']),'notes.md');r=await fetch(base+'/api/import',{method:'POST',body:f});assert.equal(r.status,201);assert.match((await r.json()).sections[0].text,/superkey/);checks.push('Multipart note import succeeds');
f=new FormData();f.append('file',new Blob(['bad']),'bad.exe');r=await fetch(base+'/api/import',{method:'POST',body:f});assert.equal(r.status,400);checks.push('Unsupported upload rejected');
writeFileSync('evidence/http-check.json',JSON.stringify({at:new Date().toISOString(),checks,passed:checks.length},null,2));console.log(checks.join('\n'));}finally{child.kill();await new Promise(r=>child.on('exit',r));rmSync(dir,{recursive:true,force:true})}
