import {useEffect,useRef,useState} from 'react';
import {BookOpen,ArrowUpRight,Upload,Check,ChevronRight,FileText,PanelRightClose,PanelRightOpen,Plus,Sparkles,Shield,Command,ArrowRight,NotebookPen,RefreshCw,FlaskConical} from 'lucide-react';
import type {Course} from '../content/course';
import {api} from './api';
import {Practice} from './Practice';
import {Ask} from './Ask';
import {Notebook} from './Notebook';
import {EvidenceHub,type EvidenceExperiment} from './EvidenceHub';
import type {CurrentEvidenceData} from './CurrentEvidence';
import currentEvidence from './generated/current-evidence.json';
import {CounterexampleLab} from './CounterexampleLab';
import {QuickRoute} from './QuickRoute';
import {transferForLab,labContextForQuestion,sourceForLab,sourceForQuestion,defaultLabContext,type LabTransferContext} from './lab-transfer';
import {portable,preferences} from './environment';
import {availableCourseId,createRequestScope} from './request-scope';
export function App(){
 const[courses,setCourses]=useState<Course[]>([]),[selected,setSelected]=useState(portable?'database-foundations':preferences.get('course')||'database-foundations'),[questions,setQuestions]=useState<any[]>([]),[qid,setQid]=useState(preferences.get('question')||'null-d'),[view,setView]=useState('practice'),[status,setStatus]=useState<any>(null),[history,setHistory]=useState<any>({attempts:[],chats:[]}),[source,setSource]=useState('null-where'),[sourceOpen,setSourceOpen]=useState(true),[zh,setZh]=useState(preferences.get('language')==='zh'),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[generating,setGenerating]=useState(false),[loadingCourse,setLoadingCourse]=useState(true),[help,setHelp]=useState(false),[askPrefill,setAskPrefill]=useState(''),[freshQuestion,setFreshQuestion]=useState<string|null>(null),[practiceRun,setPracticeRun]=useState(0);
 const[labContext,setLabContext]=useState<LabTransferContext>(defaultLabContext),[labRun,setLabRun]=useState(0);
 const[evidenceVersion,setEvidenceVersion]=useState<EvidenceExperiment>('current');
 const input=useRef<HTMLInputElement>(null),initialScope=useRef(createRequestScope()),courseScope=useRef(createRequestScope()),historyScope=useRef(createRequestScope()),generationScope=useRef(createRequestScope()),statusScope=useRef(createRequestScope()),selectedRef=useRef(selected),sourceRef=useRef(source);selectedRef.current=selected;sourceRef.current=source;
 const course=courses.find(c=>c.id===selected);const question=questions.find(q=>q.id===qid);const section=course?.sections.find(s=>s.id===source)||course?.sections[0];
 const currentEvidenceView=view==='evidence'&&evidenceVersion==='current',showSource=sourceOpen&&!currentEvidenceView;
 function cancelGeneration(){generationScope.current.cancel();setGenerating(false)}
 function switchCourse(id:string,builtin:boolean){courseScope.current.cancel();historyScope.current.cancel();cancelGeneration();selectedRef.current=id;setSelected(id);setQuestions([]);setHistory({attempts:[],chats:[]});setLoadingCourse(true);setFreshQuestion(null);setView(builtin?'practice':'ask');setAskPrefill('');setError('')}
 async function refreshStatus(){const request=statusScope.current.begin();try{const next=await api('/status',undefined,request.signal);if(request.isCurrent())setStatus(next)}catch(e){if(request.isCurrent())setError((e as Error).message)}}
 async function loadHistory(courseId=selectedRef.current){const request=historyScope.current.begin();try{const next=await api(`/courses/${courseId}/history`,undefined,request.signal);if(request.isCurrent()&&selectedRef.current===courseId)setHistory(next)}catch(e){if(request.isCurrent()&&selectedRef.current===courseId)setError((e as Error).message)}}
 useEffect(()=>{const request=initialScope.current.begin();api('/courses',undefined,request.signal).then((next:Course[])=>{if(!request.isCurrent())return;setCourses(next);const valid=availableCourseId(selectedRef.current,next);if(valid!==selectedRef.current)switchCourse(valid,!!next.find(c=>c.id===valid)?.builtin)}).catch(e=>{if(request.isCurrent()){setError(e.message);setLoadingCourse(false)}});refreshStatus();return()=>{initialScope.current.cancel();courseScope.current.cancel();historyScope.current.cancel();generationScope.current.cancel();statusScope.current.cancel()}},[]);
 useEffect(()=>{if(!course)return;const courseId=selected,request=courseScope.current.begin();historyScope.current.cancel();cancelGeneration();preferences.set('course',courseId);setError('');setLoadingCourse(true);setQuestions([]);setHistory({attempts:[],chats:[]});setSource(course.sections[0]?.id||'');Promise.all([api(`/courses/${courseId}/questions`,undefined,request.signal),api(`/courses/${courseId}/history`,undefined,request.signal)]).then(([q,h])=>{if(!request.isCurrent()||selectedRef.current!==courseId)return;setQuestions(q);setHistory(h);setQid(old=>q.some((x:any)=>x.id===old)?old:q[0]?.id||'')}).catch(e=>{if(request.isCurrent()&&selectedRef.current===courseId)setError(e.message)}).finally(()=>{if(request.isCurrent()&&selectedRef.current===courseId)setLoadingCourse(false)});return()=>{courseScope.current.cancel();historyScope.current.cancel();generationScope.current.cancel()}},[selected,course]);
 useEffect(()=>{preferences.set('question',qid)},[qid]);
 useEffect(()=>{if(!course?.builtin||!question)return;const id=sourceForQuestion(question.id);if(id)setSource(id)},[course?.id,question?.id]);
 useEffect(()=>{preferences.set('language',zh?'zh':'en');document.documentElement.lang=zh?'zh':'en'},[zh]);
 useEffect(()=>{if(view==='practice'||view==='ask'||(view==='evidence'&&evidenceVersion==='original'))setSourceOpen(true)},[view,evidenceVersion]);
 function selectSource(id:string){if(id!==sourceRef.current)cancelGeneration();sourceRef.current=id;setSource(id);setSourceOpen(true);setTimeout(()=>document.getElementById('source-heading')?.focus(),30)}
 function selectQuestion(id:string,fresh=false){cancelGeneration();const nextSource=course?.builtin?sourceForQuestion(id):undefined;if(nextSource)setSource(nextSource);setQid(id);setFreshQuestion(fresh?id:null);if(fresh)setPracticeRun(n=>n+1);setView('practice');setError('')}
 function openLab(context:LabTransferContext){cancelGeneration();setLabContext(context);setLabRun(n=>n+1);setView('lab');setSource(sourceForLab(context));setError('')}
 function openLabTransfer(context:LabTransferContext){const target=transferForLab(context);setSource(target.sourceIds[0]);selectQuestion(target.questionId,true)}
 function next(){if(question?.pairedId){selectQuestion(question.pairedId);return;}const diagnostic=questions.filter(q=>q.kind!=='transfer');const current=diagnostic.findIndex(q=>q.concept===question?.concept);selectQuestion(diagnostic[(current+1)%diagnostic.length]?.id||'')}
 async function importFile(file:File){setUploading(true);setError('');const importingFrom=selectedRef.current,f=new FormData();f.append('file',file);try{const c=await api('/import',f);setCourses(old=>[...old,c]);if(selectedRef.current===importingFrom)switchCourse(c.id,false)}catch(e){setError((e as Error).message)}finally{setUploading(false);if(input.current)input.current.value=''}}
 async function generate(){if(!course||!section||generating||loadingCourse)return;const courseId=selected,sectionId=section.id,request=generationScope.current.begin();setGenerating(true);setError('');const current=()=>request.isCurrent()&&selectedRef.current===courseId&&sourceRef.current===sectionId;try{const q=await api('/generate-question',{courseId,sectionId,language:zh?'zh':'en'},request.signal);if(current()){setQuestions(old=>old.some(x=>x.id===q.id)?old:[...old,q]);selectQuestion(q.id)}}catch(e){if(current())setError((e as Error).message)}finally{if(current())setGenerating(false)}}
 function recordAttempt(r:any,courseId:string){if(selectedRef.current!==courseId)return;historyScope.current.cancel();setFreshQuestion(null);setHistory((h:any)=>({...h,attempts:h.attempts.some((a:any)=>a.id===r.id)?h.attempts:[...h.attempts,r]}));loadHistory(courseId)}
 const latestByQuestion=new Map<string,any>(history.attempts.map((x:any)=>[x.questionId,x]));const latest=latestByQuestion.get(qid);const completed=new Set([...latestByQuestion.values()].filter(x=>x.isCorrect).map(x=>x.questionId));
 return <div className="app"><a className="skip" href="#main">Skip to learning workspace</a><aside className="sidebar"><a className="brand" href={portable?'#':'/'} aria-label="TraceLearn home"><span className="brand-icon"><BookOpen size={23}/></span>TraceLearn<span className="brand-period">.</span></a><div className="sidebar-label">{zh?'你的课程':'YOUR WORKSPACE'}</div><label className="sr-only" htmlFor="course-select">Course</label><select id="course-select" value={selected} onChange={e=>{const id=e.target.value;switchCourse(id,!!courses.find(c=>c.id===id)?.builtin)}}>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><button className="import" disabled={portable||uploading} onClick={()=>input.current?.click()}><Plus size={16}/>{uploading?(zh?'正在导入…':'Importing…'):(portable?(zh?'导入材料需完整版':'Import notes in the full app'):(zh?'导入自己的材料':'Import your own notes'))}<span>↗</span></button><input ref={input} type="file" hidden accept=".pdf,.md,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f)}}/>
 <div className="sidebar-divider"/><div className="sidebar-label">{zh?'学习路径':'LEARNING PATH'}<span>{questions.filter(q=>q.kind!=='transfer').length}</span></div><nav className="concept-list" aria-label="Course concepts">{questions.filter(q=>q.kind!=='transfer').map((q,i)=><button key={q.id} className={(q.kind==='generated'?question?.id===q.id:question?.concept===q.concept)?'active':''} onClick={()=>selectQuestion(q.id)}><span className="concept-index">{completed.has(q.id)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><span>{q.kind==='generated'?`${zh?'原文填空':'Source recall'} ${i+1}`:q.concept}</span>{(q.kind==='generated'?question?.id===q.id:question?.concept===q.concept)&&<ChevronRight size={14}/>}</button>)}</nav>
 <button className="notebook-link" onClick={()=>{cancelGeneration();setView('notebook');loadHistory()}}><NotebookPen size={17}/>{zh?'学习记录':'Learning notebook'}<span>{history.attempts.length}</span></button><div className="privacy-card"><Shield size={19}/><strong>{zh?'你的材料，留在你的设备。':'Your notes. Your device.'}</strong><p>{portable?(zh?'无需安装。练习记录保存在此浏览器（若允许）。':'No installation. Practice stays in this browser when storage is allowed.'):(zh?'下载模型后离线使用。不需要API密钥。':'Runs locally after model download. No API key required.')}</p><button onClick={()=>setHelp(!help)}>{zh?'运行设置':'Local setup'}<ArrowUpRight size={12}/></button></div><div className="sidebar-footer">BUILD CHALLENGE 3.0 <span>2026</span></div></aside>
 <div className="workspace"><header className="topbar"><div><span className="breadcrumb">{zh?'课程':'Workspace'}</span><ChevronRight size={13}/><span>{course?.title||'Loading…'}</span></div><div className="top-actions"><button className="status-button" onClick={()=>{setHelp(!help);refreshStatus()}}><span className={`status-dot ${status?.ready?'on':''}`}/>{portable?(zh?'便携练习版':'Portable practice'):status?.ready?(zh?'本地AI就绪':'Local AI ready'):(zh?'设置本地AI':'Set up local AI')}</button><button className="language" onClick={()=>setZh(!zh)}>{zh?'EN':'中文'}</button></div></header>
 {help&&!portable&&<div className="setup"><div><strong>{zh?'本地运行设置':'Local runtime setup'}</strong><p>{zh?'在项目目录运行以下命令，安装模型并启动程序。首次下载约7.3GB，之后无需联网。':'Run these commands inside the project directory. First model download is approximately 7.3 GB; later inference is local.'}</p><code>npm run setup</code><code>npm start</code><p className="fineprint">{status?.model||'qwen3.5:9b'} + {status?.embedding||'qwen3-embedding:0.6b'} · 127.0.0.1 only</p></div><button className="secondary" onClick={refreshStatus}><RefreshCw size={14}/>{zh?'检查连接':'Check connection'}</button></div>}
 {portable&&<div className="portable-banner"><strong>{zh?'无需安装，直接开始。':'Open the file. Start learning.'}</strong><p>{zh?'20道练习题、可修改条件的概念实验、原文与导出。Evidence 中的AI回答是历史记录，实时问答和导入材料需完整版。':'20 practice questions, editable concept experiments, source passages and export. AI answers in Evidence are recorded; live AI and document import need the full app.'}</p>{help&&<a href="https://github.com/FENGJIA666/tracelearn/releases" target="_blank" rel="noreferrer">{zh?'获取完整本地AI版本':'Get the full local AI application'}</a>}</div>}
 <main id="main"><div className="page-heading"><div><div className="eyebrow">{course?.builtin?(zh?'原创课程 · 10组概念':'ORIGINAL COURSE · 10 CONCEPT PAIRS'):(zh?'你的私有材料':'YOUR PRIVATE SOURCE')}</div><h1>{zh?'从“我猜”到“我懂了”。':'From “I think” to “I understand.”'}</h1><p>{course?.builtin?(zh?'找到依据。定位误解。在新问题中验证理解。':'Find the evidence. Spot the misconception. Test the idea again.'):(zh?'查看引用。核对原文措辞。让材料留在本机。':'Inspect citations. Recall the wording. Keep your notes local.')}</p></div><div className="course-stamp"><span>{course?.sections.length||0}</span><small>{zh?'原文片段':'source passages'}</small></div></div>
 {course?.builtin&&<QuickRoute zh={zh} onPractice={()=>{setSource('null-comparison');selectQuestion('null-d',true)}} onLab={()=>openLab(defaultLabContext)} onTransfer={()=>{setSource('null-where');selectQuestion('null-t',true)}} onNotebook={()=>{cancelGeneration();setView('notebook');loadHistory()}}/>}
 {!course?.builtin&&<div className="journey" aria-label="Learning workflow"><span><span>1</span>{zh?'阅读原文':'Read source'}</span><i/><span><span>2</span>{zh?'核对措辞':'Recall wording'}</span><i/><span><span>3</span>{zh?'复习与导出':'Review & export'}</span></div>}
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>{zh?'关闭':'Dismiss'}</button></div>}
 <div className={`learning-grid ${showSource?'':'source-hidden'}`}><div className="learning-panel"><div className="tabs" role="tablist" aria-label="Learning mode">{[['practice',zh?'练习':'Practice',BookOpen],...(!portable?[['ask',zh?'询问原文':'Ask the source',Sparkles]]:[]),...(course?.builtin?[['lab',zh?'概念实验':'Lab',FlaskConical],['evidence',zh?'实验记录':'Evidence',FileText]]:[]),['notebook',zh?'学习记录':'Notebook',NotebookPen]].map(([v,label,Icon]:any)=><button key={v} role="tab" aria-selected={view===v} onClick={()=>{cancelGeneration();setView(v);if(v==='notebook')loadHistory()}} className={view===v?'active':''}><Icon size={15}/>{label}</button>)}{!currentEvidenceView&&<button className="source-toggle" title={zh?'显示/隐藏原文':'Toggle source'} aria-label="Toggle source" onClick={()=>setSourceOpen(!sourceOpen)}>{sourceOpen?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</button>}</div>
 {loadingCourse&&<div className="thinking" role="status"><div className="pulse"/><p>{zh?'正在加载课程和学习记录…':'Loading this course and its learning trail…'}</p></div>}
 {view==='practice'&&!loadingCourse&&<Practice key={`${selected}:${qid}:${practiceRun}`} question={question} previous={freshQuestion===qid?undefined:latest} onAnswered={r=>recordAttempt(r,selected)} onNext={next} onSource={selectSource} onExperiment={labContextForQuestion(qid)?()=>openLab(labContextForQuestion(qid)!):undefined} onExplain={prompt=>{setAskPrefill(prompt);setView(portable?'evidence':'ask')}} zh={zh}/>}
 {view==='ask'&&!portable&&!loadingCourse&&<Ask key={selected} courseId={selected} ready={!!status?.ready} onSource={selectSource} onDone={()=>loadHistory(selected)} prefill={askPrefill} zh={zh}/>}
 {view==='lab'&&course?.builtin&&!loadingCourse&&<CounterexampleLab key={`${course.hash}:${labRun}`} sourceHash={course.hash} zh={zh} onSource={selectSource} onContext={setSource} initialContext={labContext} onTransfer={openLabTransfer}/>}
 {view==='evidence'&&course?.builtin&&!loadingCourse&&<EvidenceHub data={currentEvidence as CurrentEvidenceData} onSource={selectSource} zh={zh} version={evidenceVersion} onVersionChange={setEvidenceVersion}/>}
 {view==='notebook'&&!loadingCourse&&<Notebook questions={questions} onPractice={id=>selectQuestion(id,true)} history={history} courseId={selected} onSource={selectSource} zh={zh}/>}
 {course&&!course.builtin&&<div className="generate-row"><button className="secondary" disabled={!status?.ready||generating||loadingCourse||!section} onClick={generate}><Sparkles size={15}/>{generating?(zh?'正在生成…':'Generating…'):(zh?'为当前片段生成练习':'Generate from this passage')}</button>{generating&&<button className="text-button" onClick={()=>{cancelGeneration();setError(zh?'已取消生成':'Generation cancelled')}}>{zh?'取消':'Cancel'}</button>}<p className="fineprint">{zh?'为原文面板当前显示的片段生成填空。答案按原文逐字核对；已用过的句子不会重复生成。':'Create source recall from the passage shown in the source panel. Answers match the original quote; previously used statements are skipped.'}</p></div>}
 </div>
 {showSource&&<aside className="source-panel" aria-label="Source evidence"><div className="source-header"><FileText size={16}/><span>{zh?'回到原文':'BACK TO THE SOURCE'}</span><span className="badge">{zh?'本地':'LOCAL'}</span></div><div className="source-content"><div className="page-label">{course?.builtin?'ORIGINAL TEACHING NOTES':course?.title} <span>p. {section?.page}</span></div><h2 id="source-heading" tabIndex={-1}>{section?.title}</h2><div className="source-rule"/><p className="source-text">{zh&&section?.textZh?section.textZh:section?.text}</p>{section?.id==='null-where'&&<div className="sql-example"><div>SQL · THREE-VALUED LOGIC</div><code>salary &lt;&gt; 100</code><table><thead><tr><th>salary</th><th>predicate</th><th>WHERE</th></tr></thead><tbody><tr><td>100</td><td>FALSE</td><td>excluded</td></tr><tr className="keep"><td>200</td><td>TRUE</td><td>✓ kept</td></tr><tr><td>NULL</td><td>UNKNOWN</td><td>excluded</td></tr></tbody></table></div>}<div className="source-id"><Command size={12}/>{section?.id}</div><p className="fineprint">{zh?'原文依据可核对。AI解释仍需判断。':'Source text is inspectable. AI interpretations still need judgment.'}</p><label className="source-label" htmlFor="passage">{zh?'浏览原文片段':'Browse passages'}</label><select id="passage" value={section?.id||''} onChange={e=>selectSource(e.target.value)}>{course?.sections.map(s=><option value={s.id} key={s.id}>p.{s.page} · {s.title}</option>)}</select><details><summary>{zh?'来源指纹':'Source fingerprint'}</summary><code className="hash">SHA-256<br/>{course?.hash}</code><p className="fineprint">{zh?'用于识别本次使用的材料版本。':'Identifies the exact source version used for this session.'}</p></details></div></aside>}
 </div><footer className="main-footer"><span><Shield size={13}/>{zh?'本地处理 · 无账号 · 无API费用':'LOCAL PROCESSING · NO ACCOUNT · NO API FEES'}</span><span>TraceLearn 1.3 <span className="footer-dot">·</span> Follow the evidence.</span></footer></main></div></div>
}
