import {useEffect,useRef,useState} from 'react';
import {BookOpen,ArrowUpRight,Upload,Check,ChevronRight,FileText,PanelRightClose,PanelRightOpen,Plus,Sparkles,Shield,Command,ArrowRight,NotebookPen,RefreshCw} from 'lucide-react';
import type {Course} from '../content/course';
import {api} from './api';
import {Practice} from './Practice';
import {Ask} from './Ask';
import {Notebook} from './Notebook';
import {EvidenceLab} from './EvidenceLab';
import {portable,preferences} from './environment';
export function App(){
 const[courses,setCourses]=useState<Course[]>([]),[selected,setSelected]=useState(portable?'database-foundations':preferences.get('course')||'database-foundations'),[questions,setQuestions]=useState<any[]>([]),[qid,setQid]=useState(preferences.get('question')||'null-d'),[view,setView]=useState('practice'),[status,setStatus]=useState<any>(null),[history,setHistory]=useState<any>({attempts:[],chats:[]}),[source,setSource]=useState('null-where'),[sourceOpen,setSourceOpen]=useState(true),[zh,setZh]=useState(preferences.get('language')==='zh'),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[generating,setGenerating]=useState(false),[help,setHelp]=useState(false),[askPrefill,setAskPrefill]=useState('');
 const input=useRef<HTMLInputElement>(null),genAbort=useRef<AbortController|null>(null);const course=courses.find(c=>c.id===selected);const question=questions.find(q=>q.id===qid);const section=course?.sections.find(s=>s.id===source)||course?.sections[0];
 async function load(){try{setCourses(await api('/courses'));setStatus(await api('/status'))}catch(e){setError((e as Error).message)}}
 async function loadHistory(){setHistory(await api(`/courses/${selected}/history`))}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!course)return;preferences.set('course',selected);setError('');Promise.all([api(`/courses/${selected}/questions`),api(`/courses/${selected}/history`)]).then(([q,h])=>{setQuestions(q);setHistory(h);setQid(old=>q.some((x:any)=>x.id===old)?old:q[0]?.id||'');setSource(course.sections[0]?.id)}).catch(e=>setError(e.message));return()=>genAbort.current?.abort()},[selected,courses.length]);
 useEffect(()=>{preferences.set('question',qid)},[qid]);
 useEffect(()=>{preferences.set('language',zh?'zh':'en');document.documentElement.lang=zh?'zh':'en'},[zh]);
 function selectSource(id:string){setSource(id);setSourceOpen(true);setTimeout(()=>document.getElementById('source-heading')?.focus(),30)}
 function selectQuestion(id:string){setQid(id);setView('practice');setError('')}
 function next(){if(question?.pairedId){selectQuestion(question.pairedId);return;}const diagnostic=questions.filter(q=>q.kind!=='transfer');const current=diagnostic.findIndex(q=>q.concept===question?.concept);selectQuestion(diagnostic[(current+1)%diagnostic.length]?.id||'')}
 async function importFile(file:File){setUploading(true);setError('');const f=new FormData();f.append('file',file);try{const c=await api('/import',f);setCourses(old=>[...old,c]);setSelected(c.id);setView('ask')}catch(e){setError((e as Error).message)}finally{setUploading(false);if(input.current)input.current.value=''}}
 async function generate(){setGenerating(true);setError('');const c=new AbortController();genAbort.current=c;try{const q=await api('/generate-question',{courseId:selected,language:zh?'zh':'en'},c.signal);setQuestions(old=>[...old,q]);selectQuestion(q.id)}catch(e){setError(c.signal.aborted?(zh?'已取消生成':'Generation cancelled'):(e as Error).message)}finally{setGenerating(false)}}
 const latest=history.attempts.filter((x:any)=>x.questionId===qid).at(-1);const completed=new Set(history.attempts.filter((x:any)=>x.isCorrect).map((x:any)=>x.questionId));
 return <div className="app"><a className="skip" href="#main">Skip to learning workspace</a><aside className="sidebar"><a className="brand" href={portable?'#':'/'} aria-label="TraceLearn home"><span className="brand-icon"><BookOpen size={23}/></span>TraceLearn<span className="brand-period">.</span></a><div className="sidebar-label">{zh?'你的课程':'YOUR WORKSPACE'}</div><label className="sr-only" htmlFor="course-select">Course</label><select id="course-select" value={selected} onChange={e=>{const id=e.target.value;setSelected(id);setView(courses.find(c=>c.id===id)?.builtin?'practice':'ask');setAskPrefill('')}}>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><button className="import" disabled={portable||uploading} onClick={()=>input.current?.click()}><Plus size={16}/>{uploading?(zh?'正在导入…':'Importing…'):(portable?(zh?'导入材料需完整版':'Import notes in the full app'):(zh?'导入自己的材料':'Import your own notes'))}<span>↗</span></button><input ref={input} type="file" hidden accept=".pdf,.md,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f)}}/>
 <div className="sidebar-divider"/><div className="sidebar-label">{zh?'学习路径':'LEARNING PATH'}<span>{questions.filter(q=>q.kind!=='transfer').length}</span></div><nav className="concept-list" aria-label="Course concepts">{questions.filter(q=>q.kind!=='transfer').map((q,i)=><button key={q.id} className={question?.concept===q.concept?'active':''} onClick={()=>selectQuestion(q.id)}><span className="concept-index">{completed.has(q.id)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><span>{q.concept}</span>{question?.concept===q.concept&&<ChevronRight size={14}/>}</button>)}</nav>
 <button className="notebook-link" onClick={()=>setView('notebook')}><NotebookPen size={17}/>{zh?'学习记录':'Learning notebook'}<span>{history.attempts.length}</span></button><div className="privacy-card"><Shield size={19}/><strong>{zh?'你的材料，留在你的设备。':'Your notes. Your device.'}</strong><p>{portable?(zh?'无需安装。练习记录保存在此浏览器（若允许）。':'No installation. Practice stays in this browser when storage is allowed.'):(zh?'下载模型后离线使用。不需要API密钥。':'Runs locally after model download. No API key required.')}</p><button onClick={()=>setHelp(!help)}>{zh?'运行设置':'Local setup'}<ArrowUpRight size={12}/></button></div><div className="sidebar-footer">BUILD CHALLENGE 3.0 <span>2026</span></div></aside>
 <div className="workspace"><header className="topbar"><div><span className="breadcrumb">{zh?'课程':'Workspace'}</span><ChevronRight size={13}/><span>{course?.title||'Loading…'}</span></div><div className="top-actions"><button className="status-button" onClick={()=>{setHelp(!help);api('/status').then(setStatus)}}><span className={`status-dot ${status?.ready?'on':''}`}/>{portable?(zh?'便携练习版':'Portable practice'):status?.ready?(zh?'本地AI就绪':'Local AI ready'):(zh?'设置本地AI':'Set up local AI')}</button><button className="language" onClick={()=>setZh(!zh)}>{zh?'EN':'中文'}</button></div></header>
 {help&&!portable&&<div className="setup"><div><strong>{zh?'本地运行设置':'Local runtime setup'}</strong><p>{zh?'在项目目录运行以下命令，安装模型并启动程序。首次下载约3.2GB，之后无需联网。':'Run these commands inside the project directory. First model download is approximately 3.2 GB; later inference is local.'}</p><code>npm run setup</code><code>npm start</code><p className="fineprint">qwen3:4b + qwen3-embedding:0.6b · 127.0.0.1 only</p></div><button className="secondary" onClick={()=>api('/status').then(setStatus)}><RefreshCw size={14}/>{zh?'检查连接':'Check connection'}</button></div>}
 {portable&&<div className="portable-banner"><strong>{zh?'无需安装，直接开始。':'Open the file. Start learning.'}</strong><p>{zh?'20道真实练习题、原文、复习记录与导出。Evidence 中的AI回答是历史记录，实时问答和导入材料需完整版。':'20 real practice questions, source passages, review planning and export. AI answers in Evidence are recorded; live AI and document import need the full app.'}</p>{help&&<a href="https://github.com/FENGJIA666/tracelearn/releases" target="_blank" rel="noreferrer">{zh?'获取完整本地AI版本':'Get the full local AI application'}</a>}</div>}
 <main id="main"><div className="page-heading"><div><div className="eyebrow">{course?.builtin?(zh?'原创课程 · 10组概念':'ORIGINAL COURSE · 10 CONCEPT PAIRS'):(zh?'你的私有材料':'YOUR PRIVATE SOURCE')}</div><h1>{zh?'从“我猜”到“我懂了”。':'From “I think” to “I understand.”'}</h1><p>{zh?'找到依据。定位误解。在新问题中验证理解。':'Find the evidence. Spot the misconception. Test the idea again.'}</p></div><div className="course-stamp"><span>{course?.sections.length||0}</span><small>{zh?'原文片段':'source passages'}</small></div></div>
 <div className="journey" aria-label="Learning workflow"><span><span>1</span>{zh?'诊断':'Diagnose'}</span><i/><span><span>2</span>{zh?'核对证据':'Trace evidence'}</span><i/><span><span>3</span>{zh?'迁移复测':'Transfer & reflect'}</span></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>{zh?'关闭':'Dismiss'}</button></div>}
 <div className={`learning-grid ${sourceOpen?'':'source-hidden'}`}><div className="learning-panel"><div className="tabs" role="tablist" aria-label="Learning mode">{[['practice',zh?'练习':'Practice',BookOpen],...(!portable?[['ask',zh?'询问原文':'Ask the source',Sparkles]]:[]),...(course?.builtin?[['evidence',zh?'实验记录':'Evidence',FileText]]:[]),['notebook',zh?'学习记录':'Notebook',NotebookPen]].map(([v,label,Icon]:any)=><button key={v} role="tab" aria-selected={view===v} onClick={()=>setView(v)} className={view===v?'active':''}><Icon size={15}/>{label}</button>)}<button className="source-toggle" title={zh?'显示/隐藏原文':'Toggle source'} aria-label="Toggle source" onClick={()=>setSourceOpen(!sourceOpen)}>{sourceOpen?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</button></div>
 {view==='practice'&&<Practice question={question} previous={latest} onAnswered={r=>setHistory((h:any)=>({...h,attempts:[...h.attempts,r]}))} onNext={next} onSource={selectSource} onExplain={prompt=>{setAskPrefill(prompt);setView(portable?'evidence':'ask')}} zh={zh}/>}
 {view==='ask'&&!portable&&<Ask courseId={selected} ready={!!status?.ready} onSource={selectSource} onDone={loadHistory} prefill={askPrefill} zh={zh}/>}
 {view==='evidence'&&course?.builtin&&<EvidenceLab onSource={selectSource} zh={zh}/>}
 {view==='notebook'&&<Notebook questions={questions} onPractice={selectQuestion} history={history} courseId={selected} onSource={selectSource} zh={zh}/>}
 {!course?.builtin&&<div className="generate-row"><button className="secondary" disabled={!status?.ready||generating} onClick={generate}><Sparkles size={15}/>{generating?(zh?'正在生成…':'Generating…'):(zh?'生成AI练习题':'Generate an AI practice question')}</button>{generating&&<button className="text-button" onClick={()=>genAbort.current?.abort()}>{zh?'取消':'Cancel'}</button>}<p className="fineprint">{zh?'从前5个片段生成原文填空。答案按原文逐字核对。':'Verbatim source recall from the first five passages. Answers are checked against the original quote.'}</p></div>}
 </div>
 {sourceOpen&&<aside className="source-panel" aria-label="Source evidence"><div className="source-header"><FileText size={16}/><span>{zh?'回到原文':'BACK TO THE SOURCE'}</span><span className="badge">{zh?'本地':'LOCAL'}</span></div><div className="source-content"><div className="page-label">{course?.builtin?'ORIGINAL TEACHING NOTES':course?.title} <span>p. {section?.page}</span></div><h2 id="source-heading" tabIndex={-1}>{section?.title}</h2><div className="source-rule"/><p className="source-text">{zh&&section?.textZh?section.textZh:section?.text}</p>{section?.id==='null-where'&&<div className="sql-example"><div>SQL · THREE-VALUED LOGIC</div><code>salary &lt;&gt; 100</code><table><thead><tr><th>salary</th><th>predicate</th><th>WHERE</th></tr></thead><tbody><tr><td>100</td><td>FALSE</td><td>excluded</td></tr><tr className="keep"><td>200</td><td>TRUE</td><td>✓ kept</td></tr><tr><td>NULL</td><td>UNKNOWN</td><td>excluded</td></tr></tbody></table></div>}<div className="source-id"><Command size={12}/>{section?.id}</div><p className="fineprint">{zh?'原文依据可核对。AI解释仍需判断。':'Source text is inspectable. AI interpretations still need judgment.'}</p><label className="source-label" htmlFor="passage">{zh?'浏览原文片段':'Browse passages'}</label><select id="passage" value={section?.id||''} onChange={e=>setSource(e.target.value)}>{course?.sections.map(s=><option value={s.id} key={s.id}>p.{s.page} · {s.title}</option>)}</select><details><summary>{zh?'来源指纹':'Source fingerprint'}</summary><code className="hash">SHA-256<br/>{course?.hash}</code><p className="fineprint">{zh?'用于识别本次使用的材料版本。':'Identifies the exact source version used for this session.'}</p></details></div></aside>}
 </div><footer className="main-footer"><span><Shield size={13}/>{zh?'本地处理 · 无账号 · 无API费用':'LOCAL PROCESSING · NO ACCOUNT · NO API FEES'}</span><span>TraceLearn 1.1 <span className="footer-dot">·</span> Follow the evidence.</span></footer></main></div></div>
}
