import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Square,Sparkles} from 'lucide-react';
import {api} from './api';
export function Ask({courseId,ready,onSource,onDone,prefill,zh}:{courseId:string;ready:boolean;onSource:(id:string)=>void;onDone:()=>void;prefill:string;zh:boolean}){
 const[query,setQuery]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const controller=useRef<AbortController|null>(null);
 useEffect(()=>{controller.current?.abort();setResult(null);setQuery(prefill);setError('');return()=>controller.current?.abort()},[courseId,prefill]);
 async function ask(q=query){if(q.trim().length<3)return;setQuery(q);setBusy(true);setError('');setResult(null);const c=new AbortController();controller.current=c;try{const r=await api('/ask',{courseId,question:q,language:zh?'zh':'en'},c.signal);setResult(r);onDone()}catch(e){setError(c.signal.aborted?(zh?'已取消。没有保存部分答案。':'Cancelled. No partial answer was saved.'):(e as Error).message)}finally{setBusy(false)}}
 return <section className="ask"><div className="eyebrow"><Sparkles size={16}/>{zh?'本地模型 · 以原文为依据':'LOCAL AI · GROUNDED IN YOUR SOURCE'}</div><h2>{zh?'理解每个“为什么”。':'Understand the why.'}</h2><p className="muted">{zh?'只根据你的材料回答。原文不足以回答时，会直接说明。':'An explanation you can trace back. If the source does not establish the answer, we say so.'}</p><form onSubmit={e=>{e.preventDefault();ask()}}><label className="sr-only" htmlFor="question">{zh?'关于材料的问题':'Question about the source'}</label><textarea id="question" maxLength={1200} value={query} onChange={e=>setQuery(e.target.value)} placeholder={zh?'例如：为什么 NOT IN 遇到 NULL 会出问题？':'Why does NOT IN behave unexpectedly with NULL?'} rows={3}/><div className="ask-toolbar"><span>{query.length}/1200</span>{busy?<button type="button" className="secondary" onClick={()=>controller.current?.abort()}><Square size={13}/>{zh?'取消':'Cancel'}</button>:<button className="primary" disabled={!ready||query.trim().length<3}>{zh?'询问原文':'Ask the source'}<ArrowUpRight size={16}/></button>}</div></form>
 {!result&&!busy&&<div className="suggestions">{['Why does salary <> 100 exclude NULL?','How is 3NF different from BCNF?','What will be on my university exam?'].map(q=><button disabled={!ready} key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div>}
 {busy&&<div className="thinking" role="status"><div className="pulse"/><div><strong>{zh?'正在本机检索与推理':'Reading, retrieving, and reasoning locally'}</strong><p>{zh?'首次索引可能需要更久。你的文件不会离开设备。':'First-time indexing can take longer. Your document stays on this device.'}</p></div></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 {result&&<article className="ai-answer"><div className="answer-meta"><span className={`badge ${result.insufficient?'amber':'green'}`}>{result.insufficient?(zh?'证据不足':'Insufficient evidence'):(zh?'引用已定位':'Source quotes located')}</span><span>{(result.elapsedMs/1000).toFixed(1)}s · {result.model}</span></div><p className="answer-text">{result.answer}</p>{result.citations.map((c:any,i:number)=><button className="quote-card" key={i} onClick={()=>onSource(c.sectionId)}><span><BookOpen size={14}/>{c.sectionId}<ArrowUpRight size={14}/></span><q>{c.quote}</q></button>)}<p className="fineprint">{zh?'引用已经过原文匹配检查；这不保证解释正确，请核对原文。':'Quotes are checked against the source. This does not guarantee the explanation is correct.'}</p></article>}
 </section>
}
