import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Square,Sparkles} from 'lucide-react';
import {api} from './api';
import {createRequestScope} from './request-scope';
export function Ask({courseId,ready,onSource,onDone,prefill,zh}:{courseId:string;ready:boolean;onSource:(id:string)=>void;onDone:()=>void;prefill:string;zh:boolean}){
 const[query,setQuery]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const scope=useRef(createRequestScope()),context=useRef({courseId,prefill});context.current={courseId,prefill};
 useEffect(()=>{scope.current.cancel();setBusy(false);setResult(null);setQuery(prefill);setError('');return()=>scope.current.cancel()},[courseId,prefill]);
 function cancel(){scope.current.cancel();setBusy(false);setError(zh?'已取消当前请求。你可以重新提问。':'This request was cancelled. You can ask again.')}
 function changeQuery(value:string){scope.current.cancel();setBusy(false);setQuery(value);setResult(null);setError('')}
 async function ask(q=query){if(!ready||q.trim().length<3)return;setQuery(q);setBusy(true);setError('');setResult(null);const request=scope.current.begin();const current=()=>request.isCurrent()&&context.current.courseId===courseId&&context.current.prefill===prefill;try{const r=await api('/ask',{courseId,question:q,language:zh?'zh':'en'},request.signal);if(current()){setResult(r);onDone()}}catch(e){if(current())setError((e as Error).message)}finally{if(current())setBusy(false)}}
 return <section className="ask"><div className="eyebrow"><Sparkles size={16}/>{zh?'本地模型 · 以原文为依据':'LOCAL AI · GROUNDED IN YOUR SOURCE'}</div><h2>{zh?'理解每个“为什么”。':'Understand the why.'}</h2><p className="muted">{zh?'模型被要求依据所选课程解释，并在依据不足时拒答。引用会逐字核对；即使引用匹配，解释仍可能出错，请核对推理。':'The model is asked to explain from this course and decline when evidence is missing. Quotes are matched to the source; explanations can still be wrong or unsupported. Check the reasoning.'}</p><form onSubmit={e=>{e.preventDefault();ask()}}><label className="sr-only" htmlFor="question">{zh?'关于材料的问题':'Question about the source'}</label><textarea id="question" maxLength={1200} value={query} onChange={e=>changeQuery(e.target.value)} placeholder={zh?'例如：为什么 NOT IN 遇到 NULL 会出问题？':'Why does NOT IN behave unexpectedly with NULL?'} rows={3}/><div className="ask-toolbar"><span>{query.length}/1200</span>{busy?<button type="button" className="secondary" onClick={cancel}><Square size={13}/>{zh?'取消':'Cancel'}</button>:<button className="primary" disabled={!ready||query.trim().length<3}>{zh?'询问原文':'Ask the source'}<ArrowUpRight size={16}/></button>}</div></form>
 {!result&&!busy&&<div className="suggestions">{['Why does salary <> 100 exclude NULL?','How is 3NF different from BCNF?','What will be on my university exam?'].map(q=><button disabled={!ready} key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div>}
 {busy&&<div className="thinking" role="status"><div className="pulse"/><div><strong>{zh?'正在本机检索与推理':'Reading, retrieving, and reasoning locally'}</strong><p>{zh?'首次索引可能需要更久。你的文件不会离开设备。':'First-time indexing can take longer. Your document stays on this device.'}</p></div></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 {result&&<article className="ai-answer"><div className="answer-meta"><span className={`badge ${result.insufficient?'amber':'green'}`}>{result.insufficient?(zh?'证据不足':'Insufficient evidence'):(zh?'引用已定位':'Source quotes located')}</span><span>{(result.elapsedMs/1000).toFixed(1)}s · {result.model}</span></div><p className="answer-text">{result.answer}</p>{result.citations.map((c:any,i:number)=><button className="quote-card" key={i} onClick={()=>onSource(c.sectionId)}><span><BookOpen size={14}/>{c.sectionId}<ArrowUpRight size={14}/></span><q>{c.quote}</q></button>)}<p className="fineprint">{zh?'引用已经过原文匹配检查；这不保证解释正确，请核对原文。':'Quotes are checked against the source. This does not guarantee the explanation is correct.'}</p></article>}
 </section>
}
