import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,BookOpen,CornerDownRight,RotateCcw,FlaskConical} from 'lucide-react';
import {api} from './api';
import {portable} from './environment';
import {createRequestScope} from './request-scope';
export function Practice({question,previous,onAnswered,onNext,onSource,onExplain,onExperiment,zh}:{question:any;previous:any;onAnswered:(r:any)=>void;onNext:()=>void;onSource:(id:string)=>void;onExplain:(prompt:string)=>void;onExperiment?:()=>void;zh:boolean}){
 const[chosen,setChosen]=useState<number|null>(null),[confidence,setConfidence]=useState('somewhat'),[result,setResult]=useState<any>(previous),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const scope=useRef(createRequestScope()),currentQuestion=useRef(question?.id);currentQuestion.current=question?.id;
 useEffect(()=>{scope.current.cancel();setBusy(false);return()=>scope.current.cancel()},[question?.id]);
 useEffect(()=>{setChosen(previous?.chosen??null);setResult(previous);setError('');setConfidence('somewhat')},[question?.id,previous?.id]);
 if(!question)return <div className="empty"><BookOpen size={32}/><h2>{zh?'开始探索你的材料':'Your next insight starts here'}</h2><p>{zh?'在“询问原文”中提问，或生成一道练习题。':'Ask a question about your source, or generate an AI practice question.'}</p></div>;
 const isSourceRecall=question.kind==='generated';
 async function submit(){if(chosen===null||busy)return;const id=question.id,request=scope.current.begin();setBusy(true);setError('');const current=()=>request.isCurrent()&&currentQuestion.current===id;try{const r=await api('/attempt',{questionId:id,chosen,confidence},request.signal);if(current()){setResult(r);onAnswered(r)}}catch(e){if(current())setError(String((e as Error).message))}finally{if(current())setBusy(false)}}
 function explain(){if(!result)return;const context=`In this question: ${question.prompt} I chose "${question.options[result.chosen]}". The answer key says "${question.options[result.correct]}". `;onExplain(context+(isSourceRecall?'This is verbatim source recall. Compare the wording using only the original source and cite it. An alternative wording may mean the same thing. Do not call it conceptually false merely because it differs from the exact quote, and do not infer a learner misconception from a wording mismatch.':'Explain the reasoning using only the course source, including why my choice is correct or incorrect.'))}
 return <section className="practice">
 <div className="eyebrow"><span className="step-number">{question.kind==='transfer'?'02':'01'}</span>{question.kind==='transfer'?(zh?'迁移复测':'TRANSFER CHECK'):question.kind==='generated'?(zh?'AI生成 · 原文填空':'AI-GENERATED · SOURCE RECALL'):(zh?'概念诊断':'CONCEPT CHECK')}</div>
 <h2>{question.prompt}</h2>
 <p className="muted">{isSourceRecall?(zh?'选择与原文完全一致的措辞。同义表达也可能不匹配；此题不判断概念理解。':'Choose the exact source wording. Equivalent wording may not match; this exercise does not assess conceptual understanding.'):(zh?'选择一个答案。英文原题保留精确的数据库术语。':'Choose one answer. A confident mistake is an opportunity to learn.')}</p>
 <fieldset className="options" disabled={busy||!!result}><legend className="sr-only">{zh?'选择答案':'Select an answer'}</legend>{question.options.map((o:string,i:number)=><label key={i} className={`option ${chosen===i?'selected':''} ${result&&i===result.correct?'correct':''} ${result&&chosen===i&&!result.isCorrect?'incorrect':''}`}><input type="radio" name="answer" checked={chosen===i} onChange={()=>setChosen(i)}/><span className="letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{result&&i===result.correct&&<Check size={18}/>}</label>)}</fieldset>
 {!result?<><div className="confidence"><span>{isSourceRecall?(zh?'对原文措辞有多确定？':'How sure are you about the wording?'):(zh?'你有多确定？':'How sure are you?')}</span><div>{[['unsure',zh?'不确定':'Unsure'],['somewhat',zh?'比较确定':'Somewhat'],['sure',zh?'很确定':'Very sure']].map(([v,l])=><button key={v} className={confidence===v?'active':''} onClick={()=>setConfidence(v)} aria-pressed={confidence===v}>{l}</button>)}</div></div><button className="primary" disabled={chosen===null||busy} onClick={submit}>{busy?(zh?'检查中…':'Checking…'):isSourceRecall?(zh?'核对原文措辞':'Check source wording'):(zh?'检查理解':'Check my understanding')}<ArrowRight size={17}/></button></>:<div className={`feedback ${result.isCorrect?'positive':'review'}`} role="status"><div className="eyebrow">{isSourceRecall?(result.isCorrect?(zh?'与原文一致':'SOURCE WORDING MATCHED'):(zh?'措辞不匹配':'WORDING DIFFERS')):result.isCorrect?(zh?'回答正确':'ANSWER CORRECT'):(zh?'发现值得复习的地方':'A USEFUL GAP TO EXPLORE')}</div><h3>{result.isCorrect?(isSourceRecall?(zh?'你找到了原文中的准确表达。':'You matched the original source statement.'):question.kind==='transfer'?(zh?'你成功应用了这个概念。':'You applied the concept in a new situation.'):(zh?'现在，换个场景试试。':'Now, try the idea in a different setting.')):isSourceRecall?(zh?'这与原文措辞不同，不代表概念理解错误。':'This wording differs from the source; that does not establish a conceptual error.'):(zh?'回到证据，再试一次。':'Follow the evidence, then try again.')}</h3><p>{result.explanation}</p>{!isSourceRecall&&result.misconception&&<p className="misconception"><CornerDownRight size={16}/>{result.misconception}</p>}<div className="citation-row">{result.sourceIds.map((id:string)=><button className="citation" onClick={()=>onSource(id)} key={id}><BookOpen size={13}/>{id}</button>)}</div><button className="text-button" onClick={explain}>{portable?(zh?'查看历史AI评测记录':'Inspect recorded AI evaluations'):isSourceRecall?(zh?'用本地AI核对措辞':'Compare the wording with local AI'):(zh?'用本地AI深入解释':'Explore this reasoning with local AI')}</button><div className="feedback-actions">{onExperiment&&<button className="secondary" onClick={onExperiment}><FlaskConical size={15}/>{zh?'改条件，验证这个概念':'Change it in the lab'}</button>}{question.kind!=='generated'&&<button className="primary" onClick={onNext}>{question.pairedId?(zh?'用新问题复测':'Try the transfer check'):(zh?'下一个概念':'Next concept')}<ArrowRight size={16}/></button>}<button className="text-button" onClick={()=>{setResult(null);setChosen(null)}}><RotateCcw size={14}/>{zh?'重做':'Retry'}</button></div></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 </section>
}
