import {useEffect,useState} from 'react';
import {ArrowRight,Check,BookOpen,CornerDownRight,RotateCcw} from 'lucide-react';
import {api} from './api';
export function Practice({question,previous,onAnswered,onNext,onSource,onExplain,zh}:{question:any;previous:any;onAnswered:(r:any)=>void;onNext:()=>void;onSource:(id:string)=>void;onExplain:(prompt:string)=>void;zh:boolean}){
 const[chosen,setChosen]=useState<number|null>(null),[confidence,setConfidence]=useState('somewhat'),[result,setResult]=useState<any>(previous),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setChosen(previous?.chosen??null);setResult(previous);setError('');setConfidence('somewhat')},[question?.id,previous?.id]);
 if(!question)return <div className="empty"><BookOpen size={32}/><h2>{zh?'开始探索你的材料':'Your next insight starts here'}</h2><p>{zh?'在“询问原文”中提问，或生成一道练习题。':'Ask a question about your source, or generate an AI practice question.'}</p></div>;
 async function submit(){setBusy(true);setError('');try{const r=await api('/attempt',{questionId:question.id,chosen,confidence});setResult(r);onAnswered(r)}catch(e){setError(String((e as Error).message))}finally{setBusy(false)}}
 return <section className="practice">
 <div className="eyebrow"><span className="step-number">{question.kind==='transfer'?'02':'01'}</span>{question.kind==='transfer'?(zh?'迁移复测':'TRANSFER CHECK'):question.kind==='generated'?(zh?'AI生成 · 原文填空':'AI-GENERATED · SOURCE RECALL'):(zh?'概念诊断':'CONCEPT CHECK')}</div>
 <h2>{question.prompt}</h2>
 <p className="muted">{zh?'选择一个答案。英文原题保留精确的数据库术语。':'Choose one answer. A confident mistake is an opportunity to learn.'}</p>
 <fieldset className="options" disabled={busy||!!result}><legend className="sr-only">{zh?'选择答案':'Select an answer'}</legend>{question.options.map((o:string,i:number)=><label key={i} className={`option ${chosen===i?'selected':''} ${result&&i===result.correct?'correct':''} ${result&&chosen===i&&!result.isCorrect?'incorrect':''}`}><input type="radio" name="answer" checked={chosen===i} onChange={()=>setChosen(i)}/><span className="letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{result&&i===result.correct&&<Check size={18}/>}</label>)}</fieldset>
 {!result?<><div className="confidence"><span>{zh?'你有多确定？':'How sure are you?'}</span><div>{[['unsure',zh?'不确定':'Unsure'],['somewhat',zh?'比较确定':'Somewhat'],['sure',zh?'很确定':'Very sure']].map(([v,l])=><button key={v} className={confidence===v?'active':''} onClick={()=>setConfidence(v)} aria-pressed={confidence===v}>{l}</button>)}</div></div><button className="primary" disabled={chosen===null||busy} onClick={submit}>{busy?(zh?'检查中…':'Checking…'):(zh?'检查理解':'Check my understanding')}<ArrowRight size={17}/></button></>:<div className={`feedback ${result.isCorrect?'positive':'review'}`} role="status"><div className="eyebrow">{result.isCorrect?(zh?'回答正确':'ANSWER CORRECT'):(zh?'发现值得复习的地方':'A USEFUL GAP TO EXPLORE')}</div><h3>{result.isCorrect?(question.kind==='generated'?(zh?'你找到了原文中的准确表达。':'You matched the original source statement.'):question.kind==='transfer'?(zh?'你成功应用了这个概念。':'You applied the concept in a new situation.'):(zh?'现在，换个场景试试。':'Now, try the idea in a different setting.')):(zh?'回到证据，再试一次。':'Follow the evidence, then try again.')}</h3><p>{result.explanation}</p>{result.misconception&&<p className="misconception"><CornerDownRight size={16}/>{result.misconception}</p>}<div className="citation-row">{result.sourceIds.map((id:string)=><button className="citation" onClick={()=>onSource(id)} key={id}><BookOpen size={13}/>{id}</button>)}</div><button className="text-button" onClick={()=>onExplain(`In this question: ${question.prompt} I chose "${question.options[result.chosen]}". The answer key says "${question.options[result.correct]}". Explain the reasoning using only the course source, including why my choice is correct or incorrect.`)}>{zh?'用本地AI深入解释':'Explore this reasoning with local AI'}</button><div className="feedback-actions">{question.kind!=='generated'&&<button className="primary" onClick={onNext}>{question.pairedId?(zh?'用新问题复测':'Try the transfer check'):(zh?'下一个概念':'Next concept')}<ArrowRight size={16}/></button>}<button className="text-button" onClick={()=>{setResult(null);setChosen(null)}}><RotateCcw size={14}/>{zh?'重做':'Retry'}</button></div></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 </section>
}
