import {ArrowUpRight,BookOpen} from 'lucide-react';
type Citation={sectionId:string;quote:string};
type AnswerResult={answer:string;insufficient:boolean;citations:Citation[];elapsedMs:number;model:string;sources?:Array<{id:string;title:string}>;support?:{outcome:'supported'|'insufficient'|'unverified';claims:Array<{text:string;citations:Citation[]}>;modelCalls:number}};
export function SupportAnswer({result,zh,onSource}:{result:AnswerResult;zh:boolean;onSource:(id:string)=>void}){
 const outcome=result.support?.outcome??(result.insufficient?'insufficient':'legacy');
 const labels={supported:zh?'自动支持检查通过':'Automated support checks passed',insufficient:zh?'所选原文不足以回答':'Selected sources are insufficient',unverified:zh?'回答未通过本地检查':'No answer passed local checks',legacy:zh?'引用已定位':'Source quotes located'};
 const quotes=(citations:Citation[])=>citations.map((c,i)=><button className="quote-card" key={`${c.sectionId}-${i}`} onClick={()=>onSource(c.sectionId)}><span><BookOpen size={14}/>{c.sectionId}<ArrowUpRight size={14}/></span><q>{c.quote}</q></button>);
 return <article className="ai-answer"><div className="answer-meta"><span className={`badge ${result.insufficient?'amber':'green'}`}>{labels[outcome]}</span><span>{(result.elapsedMs/1000).toFixed(1)}s · {result.model}</span></div>
 {outcome==='supported'&&result.support?<ol className="answer-claims">{result.support.claims.map((claim,i)=><li key={i}><span className="eyebrow">{result.support!.claims.length===1?(zh?'结论':'CONCLUSION'):`${zh?'主张':'CLAIM'} ${i+1}`}</span><p className="answer-text">{claim.text}</p>{quotes(claim.citations)}</li>)}</ol>:<><p className="answer-text">{result.answer}</p>{quotes(result.citations)}</>}
 {result.support&&<details className="support-checks"><summary>{zh?'这次检查做了什么？':'What did these checks do?'}</summary><p>{zh?'先逐字核对引用，再用同一个本地模型的另一次调用检查每条主张和问题是否得到完整回答。只有通过的主张会组成最终解释。':'Quotes are matched exactly. A separate call to the same local model reviews each claim and whether the whole question was answered. Only accepted claims form the explanation.'}</p><p>{zh?'这是自动检查，不能保证正确，也不是独立人工验证。检查仅覆盖本次检索的原文片段。':'This is an automated check, not independent human verification or a guarantee of correctness. It covers only the passages retrieved for this question.'}</p><small>{zh?'本次模型调用':'Model calls this request'}: {result.support.modelCalls}</small></details>}
 {result.insufficient&&!!result.sources?.length&&<div className="retrieved-sources"><h3>{zh?'自行核对检索片段':'Inspect the retrieved passages'}</h3>{result.sources.map(s=><button className="citation" key={s.id} onClick={()=>onSource(s.id)}>{s.title}<ArrowUpRight size={12}/></button>)}</div>}
 <p className="fineprint">{zh?'请核对原文与推理。即使所有检查通过，解释仍可能出错。':'Check the source and the reasoning. An explanation can still be wrong even when every check passes.'}</p></article>;
}
